### ISSUE TITLE
Create a Dockerfile for this

### ISSUE THREAD

**Issue by marijngiesen** [acockburn/hadashboard#9] opened 2016-08-08 07:26 UTC
It would be awesome if we could have the possibility to run this in Docker, just like HA itself.

**Comment by acockburn** [comment] 2016-08-08 12:08
I don;t have any experience with Docker but I'll take a look.

**Comment by cellerich** [comment] 2016-08-09 07:18
I'm about to create a dockerfile for hadasboard based on Ubuntu (Raspi next), but did not get it to work till now. Will post any progress as soon as time allows!
Thanks for your effort @acockburn for this project!

**Comment by snizzleorg** [comment] 2016-08-09 08:04
Raps next means raspberryPi ? - Yay!

**Comment by marijngiesen** [comment] 2016-08-09 08:08
I do have experience with Docker, so I'll try to create a working Dockerfile when I have time.

**Comment by cellerich** [comment] 2016-08-09 08:19
What I found out so far that one has to expose two directories to the host (lib and dashboards) and as well the Port 3030. So my docker call looks like:

`docker run -it -v /home/cellerich/hadashboard/lib:/hadashboard/lib -v /home/cellerich/hadashboard/dashboards:/hadashboard/dashboards -p 3030:3030 cellerich/hdb261 /bin/bash`

**Comment by cellerich** [comment] 2016-08-09 09:22
And here is the dockerfile I'm using at the moment:

```
FROM ruby:2.2.5
MAINTAINER Cello Spring <cello@cello.ch>

RUN apt-get update && apt-get upgrade
RUN apt-get install -y postgresql-9.4 postgresql-server-dev-9.4 libpq-dev sqlite libsqlite3-dev node
RUN git clone https://github.com/home-assistant/hadashboard.git && \
    cd hadashboard && \
    gem install dashing && \
    gem install bundler && \
    bundle

EXPOSE 3030 

VOLUME /hadashboard/lib /hadashboard/dashboards

CMD cd hadashboard && dashing start
```

**Comment by snizzleorg** [comment] 2016-08-09 09:31
This is on a raspberryPi?

**Comment by cellerich** [comment] 2016-08-09 09:39
Hi @snizzleorg 
No, I dont think this will work with RasPi. The ruby:2.2.5 base dockerfile is based on ubuntu. But there is a RasPi ruby version on dockerhub. I did not have time to check this out. I would like to get it working on my VirtualBox first before I dig into RasPi issues :-)

**Comment by snizzleorg** [comment] 2016-08-09 11:40
why is postgresql-server necessary?

**Comment by acockburn** [comment] 2016-08-09 12:15
Thanks - I appreciate your efforts, and hope to learn enough about docker along the way that I can use it in other projects.

I did some experimenting when I rebuilt my HA host on Ubuntu a couple of days ago and I can confirm that postgress is not required as we run dashing in dev mode so only SQLLite is required - I have removed that dependency from the next version.

**Comment by snizzleorg** [comment] 2016-08-09 13:18
```
FROM hypriot/rpi-ruby
MAINTAINER Cello Spring <cello@cello.ch>

RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y libpq-dev sqlite libsqlite3-dev node git
RUN git clone https://github.com/home-assistant/hadashboard.git && \
    cd hadashboard && \
    gem install dashing && \
    gem install bundler && \
    bundle

EXPOSE 3030

VOLUME /hadashboard/lib /hadashboard/dashboards

CMD cd hadashboard && dashing start
```

is the Dockerfile I use for the raspberryPi.

Note the -y here: `RUN apt-get update && apt-get upgrade -y`

however the building of hadashboard still fails:

```
 ---> Running in 4c507f6f34c7
Cloning into 'hadashboard'...
Successfully installed rack-1.5.5
Successfully installed tilt-1.4.1
Successfully installed multi_json-1.12.1
Successfully installed hike-1.2.3
Successfully installed sprockets-2.10.2
Successfully installed thor-0.19.1
Successfully installed thread_safe-0.3.5
Successfully installed tzinfo-1.2.2
Successfully installed rufus-scheduler-2.0.24
Successfully installed daemons-1.2.4
Building native extensions.  This could take a while...
ERROR:  Error installing dashing:
        ERROR: Failed to build gem native extension.

    /usr/local/bin/ruby -r ./siteconf20160809-16-1f3xcy1.rb extconf.rb
checking for main() in -lcrypto... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/usr/local/bin/$(RUBY_BASE_NAME)
        --with-ssl-dir
        --without-ssl-dir
        --with-ssl-include
        --without-ssl-include=${ssl-dir}/include
        --with-ssl-lib
        --without-ssl-lib=${ssl-dir}/lib
        --with-openssl-config
        --without-openssl-config
        --with-pkg-config
        --without-pkg-config
        --with-cryptolib
        --without-cryptolib
/usr/local/lib/ruby/2.2.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
        from /usr/local/lib/ruby/2.2.0/mkmf.rb:541:in `try_link0'
        from /usr/local/lib/ruby/2.2.0/mkmf.rb:556:in `try_link'
        from /usr/local/lib/ruby/2.2.0/mkmf.rb:735:in `try_func'
        from /usr/local/lib/ruby/2.2.0/mkmf.rb:966:in `block in have_library'
        from /usr/local/lib/ruby/2.2.0/mkmf.rb:911:in `block in checking_for'
        from /usr/local/lib/ruby/2.2.0/mkmf.rb:351:in `block (2 levels) in postpone'
        from /usr/local/lib/ruby/2.2.0/mkmf.rb:321:in `open'
        from /usr/local/lib/ruby/2.2.0/mkmf.rb:351:in `block in postpone'
        from /usr/local/lib/ruby/2.2.0/mkmf.rb:321:in `open'
        from /usr/local/lib/ruby/2.2.0/mkmf.rb:347:in `postpone'
        from /usr/local/lib/ruby/2.2.0/mkmf.rb:910:in `checking_for'
        from /usr/local/lib/ruby/2.2.0/mkmf.rb:961:in `have_library'
        from extconf.rb:8:in `block in check_libs'
        from extconf.rb:8:in `each'
        from extconf.rb:8:in `all?'
        from extconf.rb:8:in `check_libs'
        from extconf.rb:95:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /usr/local/bundle/gems/eventmachine-1.2.0.1 for inspection.
Results logged to /usr/local/bundle/extensions/armv7l-linux/2.2.0-static/eventmachine-1.2.0.1/gem_make.out
The command '/bin/sh -c git clone https://github.com/home-assistant/hadashboard.git &&     cd hadashboard &&     gem install dashing &&     gem install bundler &&     bundle' returned a non-zero code: 1
```

probably ruby-dev needs to be installed as well. It's a slow process. but I'll keep you posted

**Comment by acockburn** [comment] 2016-08-09 13:22
A lot of these errors and solutions are captured in the README, also the thread itself has some info - hopefully that will speed things up for you.

**Comment by snizzleorg** [comment] 2016-08-10 14:29
unfortunately not. I tried to install the dependencies listed in the realm but the error remains the same

**Comment by marijngiesen** [comment] 2016-08-10 21:26
Ok, I've created a working Dockerfile. See pull request #11

**Comment by snizzleorg** [comment] 2016-08-11 17:17
I have had success with this here on a RPI2

```
FROM hypriot/rpi-ruby
MAINTAINER Cello Spring <cello@cello.ch>

RUN apt-get update \
 && apt-get install -y \
      postgresql-9.4 \
      postgresql-server-dev-9.4 \
      sqlite \
      nodejs \
      libpq-dev \
      libssl-dev \
      libsqlite3-dev \
      ruby-dev \
      python3 \
      python3-pip \
 && mkdir /app \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY . .

RUN gem install dashing \
 && gem install bundler \
 && bundle \
 && pip3 install daemonize sseclient configobj \
 && pip3 install --upgrade requests


EXPOSE 3030

VOLUME /app/lib /app/dashboards /app/hapush

CMD /app/hapush/hapush.py -d /app/hapush/hapush.cfg && dashing start
```

and using this to run:

```
docker run -d -v /home/steffen/src/hadashboard/dashboards:/app/dashboards -v /home/steffen/src/hadashboard/lib/:/app/lib/ -v /home/steffen/src/hadashboard/hapush/hapush.cfg:/app/hapush/hapush.cfg -e "TZ=Europe/Amsterdam" --net=host snizzleorg/hadashboard
```

**Comment by acockburn** [comment] 2016-08-11 17:21
See the PR and will work on it this weekend - thanks!

**Comment by cellerich** [comment] 2016-08-12 07:55
@snizzleorg 
When you create a new dockerfile you should can change the MAINTAINER to your name and e-mail. So people know that you are the one with the deep knowledge behind the file :-)

**Comment by snizzleorg** [comment] 2016-08-12 08:47
yeah - right - except I'm not the one with the deep knowledge here. I only changed the base image to something raspberry Pi compatible....

However I can say its working nicely.

**Comment by acockburn** [comment] 2016-08-12 12:58
@snizzleorg - can you send me a PR please and I'll add it to the base.

**Comment by snizzleorg** [comment] 2016-08-12 13:26
@acockburn here's the pull request (https://github.com/home-assistant/hadashboard/pull/13). I based this off @cellerich fork he deserves the credit for the docker file as the only thing i did was switching the base image to a RPI base image.

https://github.com/home-assistant/hadashboard/pull/13

**Comment by acockburn** [comment] 2016-08-12 13:34
Thanks!

**Comment by marijngiesen** [comment] 2016-08-14 08:50
@acockburn Why did you remove the Dockerfiles?

**Comment by acockburn** [comment] 2016-08-14 12:19
I explained on the forum thread - I wanted to make a release but I was still figuring out the docker stuff - it will be in the next release, never fear!

**Comment by acockburn** [comment] 2016-08-14 14:39
Part of the problem is that it isn't working on my platform - I wanted to do a retest from scratch to confirm but it looks like it is silently erroring out and it seems related to the daemonization piece, I need to debug. What OS and docker version did you test with?

**Comment by acockburn** [comment] 2016-08-14 16:23
Have it running now - will be pushing a release later today.

**Comment by acockburn** [comment] 2016-08-14 18:49
All tested and written up.

**Closed as completed by acockburn** 2016-08-14 18:49 UTC

**Comment by marijngiesen** [comment] 2016-08-14 19:20
Awesome! :)
